### PR TITLE
Implemented some validator features

### PR DESCRIPTION
**Pull request by jtavak**
- Implemented Validator class with basic account fetching features.
- Wrote unit tests for Validator class

I'm using @DuckPhamTV 's code for the BaseClient class with some minor changes to comments.

### CODE REVIEW

**Comment by shahraizali** [comment]
Hi! cool which issue is it related to, I think we don't have the issue added to Github yet?

**Comment by jtavak** [comment]
Just some stuff from the google doc https://docs.google.com/document/d/1ZJM0I53cM_YyBHoT--c_EYLSxHLz9wb2EG3LtVHh0z4/edit?usp=sharing.

**Comment by shahraizali** [comment]
@jtavak  I have created an issue to track this #13. let me know if this looks good.

**Comment by jtavak** [comment]
Yeah, looks good to me.

**Comment by shahraizali** [comment]
Hi @jtavak! tested the code looks great. awesome job 👍 . The comments I think can be a bit improved by adding the params description as well current ones are self-explanatory though like 'block_identifier' and 'account_number' but I was thinking going forward we might need these descriptions for other params so to be consistent we can add them now. @jtavak thoughts?  Other than that you nailed it 🎉

**Comment by jtavak** [comment]
Is there a specific format I should use for describing params, like Sphinx or something?

**Comment by shahraizali** [comment]
Thank you. the one you used looks good 👍

**Comment by shahraizali** [comment]
kindly comment your account number as well, Thank You.

**Comment by shahraizali** [comment]
@angle943 kindly pay this one as well #13

**Comment by jtavak** [comment]
Account number: 55bce9177483a0e4b1afc6f431c1f6104d3b84c6e6444fd978c33e9c031807bf

**Comment by odetolataiwo** [comment]
Paid

**Pull request merged**
