### PR TITLE
Set max line length back to "79"

### LINKED ISSUE #41: Set max line length back to "79" to adhere to the PEP 8 code styling
Reasoning and conclusion can be found here:
https://github.com/thenewboston-developers/thenewboston-python-client/pull/40#discussion_r525297531

### PR DESCRIPTION
**Pull request by sdhiaeddine**
Fixes #41

Max line length is set to "79"

### CODE REVIEW

**Comment by sbalasa** [comment]
@sdhiaeddine Test failed, change the lines in all the files, `flake8 .` will show you the lines having length > 79

**Comment by vosi** [comment]
What's the ratio behind <120 ?

**Comment by CirXe0N** [comment]
@sdhiaeddine  Do you need help with this?

**Comment by sbalasa** [comment]
@sdhiaeddine - Are you working on this ?

**Comment by velibor7** [comment]
I messaged him on slack but he didn't answer there either :/ 
@CirXe0N if you are working on something else I can take it :)

**Comment by sbalasa** [comment]
Okay @velibor7 you take it

**Comment by sbalasa** [comment]
Closed with https://github.com/thenewboston-developers/thenewboston-python-client/pull/61

**Pull request closed without merging**
