### PR TITLE
Bank: confirmation block + tests

### PR DESCRIPTION
**Pull request by VincentHch**
I added a function to fetch a resource given a URL because when you send a GET request for some resources (like confirmation blocks), only a part of the results are sent and a url is specified in the response. This URL points towards the next call that we need to do in order to have the following results.

### CODE REVIEW

**Comment by VincentHch** [comment]
#17

**Review by sbalasa — APPROVED** [review]
+1

**Comment by xmac11** [comment]
@VincentHch @sbalasa Aren't we going to be returning the results paginated, as we've been doing so far with the other fetch endpoints?

**Comment by VincentHch** [comment]
@xmac11 We could add different methods depending on the result we want like `fetch_all_confirmation_blocks()`

**Comment by xmac11** [comment]
Are there use cases where _all_ confirmation blocks will be needed, considering that their number will be increasing indefinitely? Does the API currently (or in the future) impose rate limiting, in which case our client will break? Do we have to provide extra functionality on top of the API?

In any case, regarding the `fetch_confirmation_blocks()` method, I would suggest keeping it consistent with the other `fetch` methods. What's your take on this @VincentHch @shahraizali ?

**Comment by VincentHch** [comment]
I agree with you. We can however left here the auxiliary methods because we might want to use them later.

**Comment by shahraizali** [comment]
Yeah, this endpoint should have pagination if its not already there. I'll test, it there are chances that it already have that since its fetching data from another endpoint but it should be able to fetch results of page 2 as well and so on. If pagination is not there lets implement that and create another PR

**Pull request merged**
