### PR TITLE
Change class methods to private #57

### PR DESCRIPTION
**Pull request by makaramkd**

### CODE REVIEW

**Review by velibor7 — APPROVED** [review]

**Review by sbalasa — APPROVED** [review]
+1

**Review by sbalasa — CHANGES_REQUESTED** [review]
Branch has a merge conflict, can you please merge the latest code from `thenewboston-developers:master` to your branch ?

**Comment by makaramkd** [comment]
> Branch has a merge conflict, can you please merge the latest code from `thenewboston-developers:master` to your branch ?

Its merged, but I will have to fix `flake8` errors that I got from it:

```
FAILED tests/banks.py::FLAKE8
FAILED tests/validators.py::FLAKE8
FAILED tnb/banks.py::FLAKE8
FAILED tnb/base_client.py::FLAKE8
FAILED tnb/validators.py::FLAKE8
```

**Comment by sbalasa** [comment]
Conflict is because of `fetch_multiple_page` function present in your branch but its been removed in the master.

**Comment by makaramkd** [comment]
Yes I know, I removed it from my branch. But when I run `pytest` after the merge I am getting failed tests for `flake8`.

**Review by shahraizali — APPROVED** [review]

**Review by sbalasa — APPROVED** [review]

**Comment by tawanike** [comment]
Hi @makaramkd , please share your account number so that we know where to send your coins. Every accepted PR gets paid. If you do not yet have an account then please download the account manager here https://thenewboston.com/download and follow these steps https://thenewboston.com/account-manager/create-an-account to create an account.

**Comment by makaramkd** [comment]
> Hi @makaramkd , please share your account number so that we know where to send your coins. Every accepted PR gets paid. If you do not yet have an account then please download the account manager here https://thenewboston.com/download and follow these steps https://thenewboston.com/account-manager/create-an-account to create an account.

Hi, this is my account number:
`b0302a7a0c02df1a5d298122de7c22a0bdd2394de75d1ae724f51a85bd13128e`

**Pull request merged**
