### PR TITLE
Done with block api

### PR DESCRIPTION
**Pull request by nishp77**
Finally solved everything rebased my whole branch, hopefully I get no merge conflicts #21

### CODE REVIEW

**Comment by sbalasa** [comment]
Still has merge conflicts, pls run `pytest`

**Comment by nishp77** [comment]
Try now

**Comment by sbalasa** [comment]
> ==== short test summary info====
> FAILED tests/banks.py::BLACK
> FAILED tests/banks.py::test_success_post_invalid_block - NameError: name 'bank' is not defined
> FAILED tests/style.py::test_style - assert not 5
> FAILED tnb/banks.py::BLACK

**Review by sbalasa — APPROVED** [review]
+1

**Comment by tawanike** [comment]
Hi @nishp77 , please share your account number so that we know where to send your coins. Every accepted PR gets paid. If you do not yet have an account then please download the account manager here https://thenewboston.com/download and follow these steps https://thenewboston.com/account-manager/create-an-account to create an account.

**Comment by nishp77** [comment]
c81061eb20ee1379ab98b6f5a125ebd0955278e36513eabd8d319967bb61d7e8

**Pull request merged**
